---
- name: install nginx
  package:
    name: "{{ nginx_package }}"
    state: present

- name: configure vhosts
  import_tasks: vhosts.yml

- name: add nginx configuration
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: ensure nginx service is running as configured
  service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
