---

- name: create dedicated user for matrix
  user:
    name: "{{ matrix_user }}"
    shell: /bin/false
    state: present

- include_tasks: postgresql.yml
  when: synapse_with_postgresql | bool

- include_tasks: synapse.yml

- include_tasks: discord.yml
