---
- name: Install matrix
  apt:
    name: matrix-synapse
    state: present

- name: UFW Allow Https
  ufw:
    rule: allow
    port: "{{ https_port }}"

- name: Deploy matrix config
  copy:
    src: homeserver.yaml
    dest: /etc/matrix-synapse/homeserver.yaml
