---
- name: Allow http
  ufw:
    rule: allow
    port: "{{ http_port }}"

- name: Allow https
  ufw:
    rule: allow
    port: "{{ https_port }}"

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Deploy nginx config
  template:
    src: landing.cfg
    dest: /etc/nginx/sites-available/landing.cfg

- name: Enable nginx config
  file:
    src: /etc/nginx/sites-available/landing.cfg
    dest: /etc/nginx/sites-enabled/landing.cfg
    state: link

- name: Restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted

- name: Install Certbot's Nginx package
  apt:
    name: python-certbot-nginx
    state: present

- name: Check if certificate already exists
  stat:
    path: /etc/letsencrypt/live/{{ inventory_hostname }}/cert.pem
  register: letsencrypt_cert

- name: Generate new certificate if one doesn't exist.
  when: not letsencrypt_cert.stat.exists
  shell: >-
    certbot --nginx --noninteractive --agree-tos
      --email notacult@bonfire.link -d {{ inventory_hostname }}
