---
- name: create acolytes' accounts
  user:
    name: "{{ item }}"
    groups: [sudo]
    shell: /bin/bash
    home: "/home/{{ item }}"
    state: present
  loop: "{{ users }}"

- name: allow password-less sudo
  copy:
    content: "%sudo  ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/ansible
    mode: 0600
    owner: root
    group: root

- name: set authorized ssh keys
  authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', 'ssh/{}.ssh'.format(item)) }}"
    state: present
  loop: "{{ users }}"

- name: disallow password authentication for ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: disallow ssh access for root
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
