---
- name: Upgrade System
  apt:
    upgrade: dist
    update_cache: yes

- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Allow ssh
  ufw:
    rule: allow
    name: ssh

- name: Deny everything else and enable UFW
  ufw:
    state: enabled
    policy: deny
    logging: "off"
