---

- include_tasks: auth.yml

- name: install common packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true

- name: open common ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ common_ports }}"

- name: open other allowed ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ allowed_ports }}"

- name: close ports and enable firewall
  ufw:
    state: enabled
    policy: deny
    logging: "off"
