---
- hosts: streamingservers
  become: true
  tasks:
    - name: show the fqdn
      debug: msg={{ tv_fqdn }}
    - name: ensure nginx is installed
      apt:
        name: nginx
        state: present
    - name: ensure nginx rtmp module is installed
      apt:
        name: libnginx-mod-rtmp
        state: present
    - name: copy the nginx config file for TV site
      copy:
        src: ../config/nginx/tv_site.cfg
        dest: "/etc/nginx/sites-available/{{ tv_fqdn }}.cfg"
        owner: root
        group: root
        mode: 0644
        force: true
    - name: copy the nginx config file for RTMP stream
      blockinfile:
        block: "{{ lookup('file', '../config/nginx/tv_stream.cfg') }}"
        dest: "/etc/nginx/nginx.conf"
    - name: create symlink for TV site
      file:
        src: "/etc/nginx/sites-available/{{ tv_fqdn }}.cfg"
        dest: "/etc/nginx/sites-enabled/{{ tv_fqdn }}.cfg"
        state: link
    - name: Check if certificate already exists.
      stat:
        path: /etc/letsencrypt/live/{{ tv_fqdn }}/cert.pem
      register: letsencrypt_cert

    - name: Generate new certificate if one doesn't exist
      when: not letsencrypt_cert.stat.exists
      shell: >-
        certbot --nginx --noninteractive --agree-tos
          --email notacult@bonfire.link -d {{ tv_fqdn }}
    - name: Create the hls dump folder
      file:
        path: /tmp/hls
        state: directory
        mode: 0777
    - name: Allow rtmp in firewall
      ufw:
        rule: allow
        port: "1935"
    - name: restart nginx
      service:
        name: nginx
        state: restarted
